### PR TITLE
Rework entities

### PR DESCRIPTION
**Pull request by ghost**
Several changes / features for Entities:
- Refactor of the entity module
- Added serialization / deserialization of Players
- Improved the integration with the combat AaribaScript:
  - Both entities are now available with `$target.*` and `$source.*`
  - Stats are available (e.g. `$source.strength`)

### CODE REVIEW

**Comment by Nemikolh** [comment]
Also, as a side note, you might want to leave more time between the moment where you create the PR and merge it. I don't think one minute is enough for letting anyone to have a chance of reviewing it. :smile: 
And this isn't a blocker for you to work on something else as well. (You're the git guy! :p)

**Comment by ghost** [comment]
Well I didn't think anybody would even look at this code ... I just used the merge request to keep those commits "together".

**Comment by Nemikolh** [comment]
> Well I didn't think anybody would even look at this code ... I just used the merge request to keep those commits "together".

The fact that you haven't been working on the project for months doesn't mean you should assume everybody else did the same. I'm personally looking at people change and give them the choice to review my work. And the fact that commits are "together" is surely an aesthetics concerns that doesn't seems to be related to having merge a PR that fast.

If this hasn't been specified in the contributions guidelines in meta then I think we should add it. @Ikyushii Do you agree with me on this or do you think 1min PR or directly pushing to master is a acceptable?

**Comment by ghost** [comment]
I didn't assume that nobody worked for the past few months (I clearly saw you and @Ikyushii did a lot).

However as only I have worked on this version of Lycan so far, I didn't think anybody would find interesting the changes I made to clean up my bad old code ...

But if you would prefer me to wait a bit for you to review, that's fine by me. I just don't like having to work on separate branches  / old code, so I avoided it as I thought it would not disturb anybody.

**Comment by ghost** [comment]
> the fact that commits are "together" is surely an aesthetics concerns

This is not entirely true. In the absolute, having well identified PR (without consideration of the merging policy) is a good idea in order to keep track of changes during a period of time; it has a great value for instance when the time comes to write a monthly review (and about thar, you might have seen I’m a little late for the last one…). Therefore, when it is possible, avoiding to push directly on master is a good practice and I am glad @Vaelden  did what he did.

Now, for the merging policy, I think whenever it is possible, we should encourage peer code review. That being said, because it is not always clear who is motivated, up and ready at a given time, it can be tricky.

I think we need to improve our team work in general, not only when it comes to merge PR. Thus, we should consider having more regular meeting to discuss all together, starting as soon as possible. During those meetings, discussing about incoming PR review (identifying a reviewer, for instance) would solve this issue, as it may happen one particular PR does not need/find one reviewer.

What do you think?

**Comment by Nemikolh** [comment]
I totally agree with you, I miss the Friday/Thursday weekly meeting for that. 

Regarding PR, the ideal would be that someone else from the PR opener merge the PR into master, everyone can then be sure that at least someone got the opportunity to test it or review it or at least have a quick chat with the PR opener to discuss it.

Besides this problem, I think we should also have more discussion about specifications of the different part of our system.

We have some internally, but it seems we fail to communicate what is the final decision or what are the unresolved questions and so on. I know this is an hard problem, but after talking to a few colleagues, I know for sure that having proper interface / APIs will save us more time in the future that what one might think.

Especially when we have disagreement on some topic, I think the problem shouldn't be marked as solve and assume that it is good to go for serious implementation.

Note that, I actually would really appreciate to have your (@Vaelden, @Ikyushii) opinion on this as well as @Azamung opinion on the matter.

**Pull request merged**
