### PR TITLE
Rewrite network to run on tokio

### PR DESCRIPTION
**Pull request by ghost**
This is a rewrite of the networking part to run on top of tokio (mio + futures) instead of plain mio.

All the network activity is now handled in a separate thread, and communicates with the `Game` or `Instance` using two point-to-point channels for each client (those are optimized to cache unused messages and should thus limit allocations).

I have currently removed all references to an event loop in other places than the network, because my precedent usage of mio EventLoop had crept everywhere and made the code difficult to understand. However, we may re-add a proper event loop later, for example to have better timeouts or more easily run several `Instance` in the same thread.

I find the resulting code overall easier to understand (once getting used to Futures / Tokio).

### CODE REVIEW

**Comment by lthms** [comment]
I take a plane in a few hours for a one week trip, so I do not know if I will be able to review this before October 24th… @Nemikolh?

**Comment by Nemikolh** [comment]
I'll have a look at it soon. Sorry for the delay.

**Comment by Nemikolh** [comment]
Ok, so I just try to do `cargo run` and it seems that I need some openssl header. Could you please edit the `README` so that it contains some indication about it? I'm not exactly sure about the step required to do that on windows though... Maybe an upstream crate has some doc we could copy/paste on that?

**Comment by Nemikolh** [comment]
Oh! and if you update the `README`, could you please add in the requirements section the minimum Rust version we require (could be the current one) and specify that we rely on the nighlty channel?

**Comment by Nemikolh** [comment]
Ok so here is what I have done:
- `cargo build` _--> Ok_
- `cargo test` _--> Err_
- `cargo run` _--> Ok_
- `./spawn_monster 0` : Got a non json object as en error message, wut?
- `./xxx`: All scripts are working, and there are really cool to use! :+1: 

I think I will merge because none of the issues I have talked about seems to be directly related to this PR.

Thanks for the hard work!

**Comment by ghost** [comment]
Yes for the `cargo test` it looks like I broke it when changing the ID format from `u64` to `Uuid`. Not really a big deal, but I will need to set up Travis at some point to avoid this kind of problems ...

**Pull request merged**
